// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinecrafCastelo12303135.Context;

#nullable disable

namespace MinecrafCastelo12303135.Migrations
{
    [DbContext(typeof(ConsultaContext))]
    partial class ConsultaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MinecrafCastelo12303135.Models.Consulta", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Material")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeJoga")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TempoGasto")
                        .HasColumnType("REAL");

                    b.HasKey("ConsultaId");

                    b.ToTable("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
